version: '3'

services:
    microservice1:
        build: microservice1/.
        image: microservice1
        container_name: microservice1
        ports: 
        - "8080:8080"
        networks:
        - my_net2
    microservice2:
        build: microservice2/.
        image: microservice2
        container_name: microservice2
        networks:
        - my_net2

networks:
    my_net2: